services:
  database:
    image: postgres:17.8-alpine
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal
  app:
    # https://github.com/hedgedoc/hedgedoc
    image: quay.io/hedgedoc/hedgedoc:1.10.6
    env_file:
      - .env
    volumes:
      - uploads:/hedgedoc/public/uploads
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - proxy
      - internal

volumes:
  database:
  uploads:

networks:
  internal:
  proxy:
    external: true
