services:
  listinator:
    image: ghcr.io/hacky-day/listinator@sha256:e78eefecf98a2a04abc7ac262415bae2f6c3588790c7d3a8cc9dae183b0fcd59
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/var/lib/listinator

  caddy:
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  data:
