---
- name: Verify galaxy roles
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - lkiesow.verify_galaxy_versions

- name: Deploy bind9 Server
  hosts: bind9
  become: true
  roles:
    - role: user_setup
      user_setup_admins:
        - name: sven
          key: file:ssh-keys/sven.pub
    - role: secure_sshd
    - role: apt_autoupdate

  tasks:
    - name: Install tools
      ansible.builtin.package:
        name:
          - bind9

    - name: Copy config files and static zone files
      ansible.builtin.template:
        src: bind9/{{ item }}
        dest: /etc/bind/{{ item }}
        owner: root
        group: bind
        mode: "0640"
      loop:
        - named.conf.options
        - named.conf.local
        - key.haardiek.org
        - db.listinator.org

    - name: Init dynamic zones
      ansible.builtin.template:
        src: bind9/{{ item }}
        dest: /var/lib/bind/{{ item }}
        owner: bind
        group: bind
        mode: "0640"
        force: false
      loop:
        - db.haardiek.org

    - name: Copy nsupdate file of haardiek.org
      ansible.builtin.template:
        src: bind9/nsupdate.haardiek.org
        dest: /etc/bind/nsupdate.haardiek.org
        owner: root
        group: bind
        mode: "0640"
      register: nsupdate_haardiek_org

    - name: Reload bind9
      service:
        name: bind9
        state: reloaded

    - name: Apply DNS updates via nsupdate for haardiek.org
      ansible.builtin.command:
        cmd: nsupdate -k "/etc/bind/key.haardiek.org" "/etc/bind/nsupdate.haardiek.org"
      when: nsupdate_haardiek_org.changed
