---
- name: Verify galaxy roles
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - lkiesow.verify_galaxy_versions

- name: Deploy Docker Server
  hosts: docker
  become: true
  roles:
    - role: user_setup
      user_setup_admins:
        - name: sven
          key: file:ssh-keys/sven.pub
    - role: secure_sshd
    - role: unattended_upgrades

  tasks:
    - name: Install tools
      ansible.builtin.package:
        name:
          - bind9-utils
          - tcpdump
          - gnupg
          - rsync

    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'

    - name: Docker apt repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/debian trixie stable
        state: present

    - name: Install Docker
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Add sven to docker group
      ansible.builtin.user:
        name: sven
        groups: docker
        append: yes
