---
- name: Verify galaxy roles
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - lkiesow.verify_galaxy_versions

- name: Deploy Tailscale Server
  hosts: tailscale
  become: true
  roles:
    - role: user_setup
      user_setup_admins:
        - name: sven
          key: file:ssh-keys/sven.pub
    - role: secure_sshd
    - role: unattended_upgrades

  tasks:
    - name: Install tools
      ansible.builtin.package:
        name:
          - bind9-utils
          - tcpdump
          - gnupg
          - ethtool
          - dnsmasq
          - bird2

    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
        keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg

    - name: Tailscale apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian bookworm main"
        state: present

    # Headscale
    - name: Install tailscale
      ansible.builtin.package:
        name: tailscale

    - name: Forward IP
      ansible.builtin.copy:
        dest: /etc/sysctl.d/99-tailscale.conf
        owner: root
        group: root
        mode: "0644"
        force: true
        content: |
          net.ipv4.ip_forward = 1
          net.ipv6.conf.all.forwarding = 1

    - name: Sysctl directly
      ansible.builtin.command: sysctl -p /etc/sysctl.d/99-tailscale.conf

    - name: Setup networking
      ansible.builtin.copy:
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: "0644"
        force: true
        content: |

          auto lo
          iface lo inet loopback

          auto eth0
          iface eth0 inet static
            address 10.0.0.2/30
            gateway 10.0.0.1
            up ethtool -K eth0 rx-udp-gro-forwarding on rx-gro-list off
      notify: Restart network

    - name: Copy Tailscale Post Script
      ansible.builtin.copy:
        dest: /opt/tailscale-post.sh
        src: files/tailscale-post.sh
        owner: root
        group: root
        mode: "0755"
        force: true

    - name: Ensure Systemd Override Directory for Tailscale
      ansible.builtin.file:
        path: /etc/systemd/system/tailscaled.service.d
        state: directory
        recurse: true
        owner: root
        group: root
        mode: "0755"
        force: true

    - name: Outgoing SNAT for Tailscale
      ansible.builtin.copy:
        dest: /etc/systemd/system/tailscaled.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
        force: true
        content: |
          [Service]
          ExecStartPost=/opt/tailscale-post.sh
      notify: Restart tailscaled

    - name: Dnsmasq Config
      ansible.builtin.copy:
        dest: /etc/dnsmasq.conf
        src: files/dnsmasq.conf
        owner: root
        group: root
        mode: "0755"
        force: true
      notify: Restart dnsmasq

    - name: Bird Config
      ansible.builtin.copy:
        dest: /etc/bird/bird.conf
        src: files/bird.conf
        owner: bird
        group: bird
        mode: "0640"
        force: true
      notify: Restart bird

  handlers:
    - name: Restart network
      ansible.builtin.service:
        name: networking
        state: restarted

    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted

    - name: Restart bird
      ansible.builtin.service:
        name: bird
        state: restarted

    - name: Restart tailscaled
      ansible.builtin.systemd_service:
        name: tailscaled
        daemon_reload: true
        state: restarted
