---

monitoring:
  hosts:
    monitoring.internal.haardiek.org:
      certificates:
        - monitoring.internal.haardiek.org
        - alertmanager.monitoring.internal.haardiek.org
        - prometheus.monitoring.internal.haardiek.org
tunnel:
  hosts:
    tunnel.haardiek.org:
      skip_node_exporter: true

proxy:
  hosts:
    proxy01.internal.haardiek.org:
      certificates:
        - nas.haardiek.org
      proxy_state: MASTER
    proxy02.internal.haardiek.org:
      certificates:
        - nas.haardiek.org
      proxy_state: BACKUP

jumphost:
  hosts:
    jumphost01.internal.haardiek.org:
      jumphost_state: MASTER
    jumphost02.internal.haardiek.org:
      jumphost_state: BACKUP

netbox:
  hosts:
    netbox.internal.haardiek.org:
      certificates:
        - netbox.internal.haardiek.org

provider:
  hosts:
    provider.internal.haardiek.org:
      certificates:
        - provider.internal.haardiek.org
