---
- name: Verify galaxy roles
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - lkiesow.verify_galaxy_versions

- name: Deploy Proxy Server
  hosts: proxy
  become: true
  roles:
    - role: user_setup
      user_setup_admins:
        - name: sven
          key: file:ssh-keys/sven.pub
    - role: secure_sshd
    - role: apt_autoupdate

  tasks:
    - name: Install tools
      ansible.builtin.package:
        name:
          - caddy

    - name: Add Tailscale GPG key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/debian/trixie.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: "0644"

    - name: Add Tailscale repository
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/debian/trixie.tailscale-keyring.list
        dest: /etc/apt/sources.list.d/tailscale.list
        mode: "0644"

    # manually run sudo tailscale up --accept-routes --login-server https://hacky.day
    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        update_cache: true

    - name: Enable and start tailscaled
      ansible.builtin.systemd:
        name: tailscaled
        enabled: true
        state: started

    - name: Deploy Caddyfile
      ansible.builtin.template:
        src: templates/proxy/Caddyfile
        dest: /etc/caddy/Caddyfile
        owner: caddy
        group: caddy
        mode: "0644"
      notify: Reload Caddy

    - name: Enable and start Caddy
      ansible.builtin.systemd:
        name: caddy
        enabled: true
        state: started

  handlers:
      - name: Reload Caddy
        ansible.builtin.systemd:
          name: caddy
          state: reloaded
