---
roles:
  - src: https://github.com/virtUOS/user_setup.git
    scm: git
    version: 1.0.0
  - src: https://github.com/UOS-RZ/secure_sshd.git
    scm: git
    version: 1.1.1
  - name: lkiesow.verify_galaxy_versions
    version: 1.0.0
