version: "2.4"
services:
  frontend:
    image: "grocy/frontend:v4.2.0"
    depends_on:
      - backend
    expose:
      - "8080"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    networks:
      - proxy

  backend:
    image: "grocy/backend:v4.2.0"
    expose:
      - "9000"
    read_only: true
    tmpfs:
      - /tmp
      - /var/www/data/viewcache:mode=755,uid=82,gid=82,size=16m
    volumes:
      - app-db:/var/www/data
    env_file:
      - grocy.env
    restart: unless-stopped
    networks:
      - proxy

volumes:
  app-db:

networks:
  proxy:
    external: true
